/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rTVrJyWxNYI
 */
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import Image from 'next/image'

export default function Main() {
  return (
    <section className="w-full pt-10 md:pt-22 lg:pt-28">
      <div className="container space-y-10 xl:space-y-16">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-medium tracking-tighter [text-wrap:balance] text-stone-800 dark:text-stone-200 sm:text-4xl md:text-5xl lg:text-6xl">
              Simplify Your Tasks with List Guy
            </h1>
            <p className="mx-auto max-w-[700px] text-stone-500 [text-wrap:balance] md:text-xl dark:text-zinc-400">
              Keep track of your tasks, big or small, with ListMaker. Easy to
              use, customizable, and always by your side.
            </p>
          </div>
          <div className="space-x-4">
            <Button asChild>
              <Link href="#">Get Started</Link>
            </Button>
            <Button asChild variant="secondary">
              <Link href="#">Learn More</Link>
            </Button>
          </div>
        </div>
        <div className="pt-16">
          <div className="relative mx-auto aspect-video max-w-4xl overflow-hidden rounded-t-xl object-cover object-center">
            <Image
              alt="ListMaker App"
              className="dark:hidden block"
              fill={true}
              src="/app-light.png"
            />
            <Image
              alt="ListMaker App"
              className="hidden dark:block"
              fill={true}
              src="/app-dark.png"
            />
          </div>
        </div>
      </div>
    </section>
  )
}
